### ISSUE TITLE
failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

### ISSUE THREAD

**Issue by mhappyyy** [rust-lang/libc#1778]
`error:` failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

```
Caused by:
  patch for `libc` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/local/mnt/workspace/mahto/rust/src/bootstrap/bootstrap.py", line 960, in main
    bootstrap(help_triggered)
  File "/local/mnt/workspace/mahto/rust/src/bootstrap/bootstrap.py", line 929, in bootstrap
    build.build_bootstrap()
  File "/local/mnt/workspace/mahto/rust/src/bootstrap/bootstrap.py", line 724, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/local/mnt/workspace/mahto/rust/src/bootstrap/bootstrap.py", line 143, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /local/mnt/workspace/mahto/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /local/mnt/workspace/mahto/rust/src/bootstrap/Cargo.toml --verbose
```

Hii, I'm trying to build rust with libc(from my local machine) where I made some changes. But I'm facing this issue. Please help. 

This is my Cargo.toml
```toml
[patch."https://github.com/rust-lang/cargo"]
cargo = { path = "src/tools/cargo" }

[patch.crates-io]
ustfmt-nightly = { path = "src/tools/rustfmt" }

#libc = { path = "../libc" }

rustc-workspace-hack = { path = 'src/tools/rustc-workspace-hack' }

rustc-std-workspace-core = { path = 'src/tools/rustc-std-workspace-core' }
rustc-std-workspace-alloc = { path = 'src/tools/rustc-std-workspace-alloc' }
rustc-std-workspace-std = { path = 'src/tools/rustc-std-workspace-std' }
libc = {path = "../mahto/libc"}

[patch."https://github.com/rust-lang/rust-clippy"]
clippy_lints = { path = "src/tools/clippy/clippy_lints" }
```

this is my cargo.lock
```
[[package]]
name = "libc"
version = "0.2.70"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3baa92041a6fec78c687fa0cc2b3fae8884f743d672cf551bed1d6dac6988d0f"
dependencies = [
 "rustc-std-workspace-core",
]
```

the version of libc on my directory is v0.2.70. and the libc directory is just outside my rust directory(path = "../libc")
Let me know if any information is required.

**Comment by JohnTitor** [comment]
As mentioned in the cargo issue, this may be resolved by removing `Cargo.lock` and re-building. Given from the error message, I believe this isn't the libc side issue so I'm going to close this as wontfix/invalid.

**Comment by mhappyyy** [comment]
I deleted the `Cargo.lock` but the error is still there.
