### ISSUE TITLE
 aarch64-apple-darwin test failure

### ISSUE THREAD

**Issue by chadbrewbaker** [rust-lang/libc#2183]
aarch64-apple-darwin rustc 1.54.0-nightly (6d395a1c2 2021-05-13) commit 4e7867d1b591439

```bash
RUNNING ALL TESTS
bad VM_FLAGS_USER_ALLOCATE value at byte 0: rust: 31 (0x1f) != c 159 (0x9f)
bad VM_FLAGS_USER_MAP value at byte 0: rust: 31 (0x1f) != c 159 (0x9f)
thread 'main' panicked at 'some tests failed', /Users/username/github/libc/target/debug/build/libc-test-621539cf11e10654/out/main.rs:12:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/std/src/panicking.rs:519:12
   1: main::main
             at /Users/crb002/github/libc/target/debug/build/libc-test-621539cf11e10654/out/main.rs:12:21
   2: core::ops::function::FnOnce::call_once
             at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass '--test main'
```

**Comment by JohnTitor** [comment]
They are declared on the `deprecated_mach` macro, which means the libc doesn't support the use of these values anymore. I think it's okay to just ignore them on tests or move to the x86_64 module if it works.
