### ISSUE TITLE
Build failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by rubberduck203** [rust-lang/libc#956]
There aren't any build instructions beyond the `cd libc-test && cargo test` command in the README.
I'm trying to build master on Ubuntu 16.04 and getting the following panic.

I'm having trouble figuring out what's going wrong here beyond it's failing in the `cc` crate.

I'm getting the same stacktrace with or without `TARGET=x86_64-unknown-linux-gnu`.

```
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-deprecated-declarations" "-Wno-deprecated-declarations" "-D_GNU_SOURCE" "-o" "/home/rubberduck/libc/target/debug/build/libc-test-822e8031de5523f8/out/main.o" "-c" "/home/rubberduck/libc/target/debug/build/libc-test-822e8031de5523f8/out/main.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/rubberduck/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.8/src/lib.rs:2049:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: cc::fail
             at /home/rubberduck/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.8/src/lib.rs:2049
   8: cc::Build::compile
             at /home/rubberduck/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.8/src/lib.rs:881
   9: ctest::TestGenerator::_generate
             at /home/rubberduck/.cargo/git/checkouts/ctest-2cf90b4dc49563d8/954f493/src/lib.rs:601
  10: ctest::TestGenerator::generate
             at /home/rubberduck/.cargo/git/checkouts/ctest-2cf90b4dc49563d8/954f493/src/lib.rs:559
  11: build_script_build::main
             at libc-test/build.rs:777
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```

**Comment by rubberduck203** [comment]
A little progress. I unwrapped the command it was trying to execute and manually tried it.

```bash
gcc -O0 -ffunction-sections -fdata-sections -fPIC -g -m64 -Wall -Wextra -Wall -Wextra -Werror -Wno-unused-parameter -Wno-type-limits -Wno-deprecated-declarations -Wno-deprecated-declarations -D_GNU_SOURCE -o /home/rubberduck/libc/target/debug/build/libc-test-822e8031de5523f8/out/main.o -c /home/rubberduck/libc/target/debug/build/libc-test-822e8031de5523f8/out/main.c
```

This results in dozens of build errors like the following.

```
/home/rubberduck/libc/target/debug/build/libc-test-822e8031de5523f8/out/main.c:5754:53: error: ‘MADV_FREE’ undeclared here(not in a function)
             static int __test_const_MADV_FREE_val = MADV_FREE;
```

I found the corresponding code in `target/debug/build/libc-test-822e8031de5523f8/out/main.c`

This is the offending line, but there are literally dozens of undeclared constants or defines.

```c
            static int __test_const_MADV_FREE_val = MADV_FREE;
```

I was doing kernel driver development on this machine a few weeks ago, so I already have the Linux headers installed on my system.

**Comment by mati865** [comment]
`MADV_FREE` is unavailable in kernels before 4.5 and Ubuntu 16.04 ships with 4.4.

**Comment by rubberduck203** [comment]
Thanks. I switched over to my Arch machine running 4.15 and it works fine.
